### ISSUE TITLE
Not able to integrate this library in Objective-c

### ISSUE THREAD

**Issue by developweb10** [lyft/Lyft-iOS-sdk#12]
Hi,

Please let me know the solution how can i integrate this library for existing app which developed in objective-c

Thanks

**Comment by acityinohio** [comment]
Unfortunately as of today the SDK only supports Swift code; see here: #11

Best,
Josh

**Comment by developweb10** [comment]
We can integrate Lyft functionality in objective-c using web api ?

**Comment by acityinohio** [comment]
👍 Sure, you are definitely free to use the web API instead of the SDK—you'll just have to make your own wrappers around the web requests in Objective C.

**Comment by developweb10** [comment]
Hi @acityinohio 

Thanks for your valuable feedback.
Can i get your personal Mail/Skype id here? Because i am getting some issue to integrate web api in app getting some bad response. Please send me your id then i can discuss with you direct.

Thanks

**Comment by acityinohio** [comment]
Best place for developer support is our open forums, which you can reach here: https://devcommunity.lyft.co/ —feel free to seek out help there (either myself or another team member will respond there). A solution to your problem might already be there on the forums, or the solution we find together might help another developer. 👍

**Comment by developweb10** [comment]
Hi @acityinohio 

Thanks to share me your valuable feedback & guide me also i have one suggestion for Lyft community, I think it will be better for all.
