### ISSUE TITLE
How to implement your pod file in objective-c ?

### ISSUE THREAD

**Issue by PGandhi30** [lyft/Lyft-iOS-sdk#14]
I had done most of thing which is available in apple guidelines to use lyft sdk in objective c but i can not implement Lyftconfiguration in objective-c.

Can i use your pod in objective-c ?

Lyftconfiguration start with 
public struct Lyftconfiguration {

}
that's why it's not possible to implement in objective-c.

If you have possible way please tell me step.

**Comment by vpolouchkine** [comment]
Unfortunately, as of today, the SDK only supports Swift code; see here: https://github.com/lyft/Lyft-iOS-sdk/issues/11.
