### ISSUE TITLE
Check Lyft availability in a specific location.

### ISSUE THREAD

**Issue by PhilippeRiegert** [lyft/Lyft-iOS-sdk#15]
Is it possible to know if the Lyft service is available in a specific location ?
Is there a way in the SDK to ask if is it possible for the user to request a Lyft at is current location ?
So I could hide the Lyft button when it's not available for my user, thanks for the help !

**Comment by vpolouchkine** [comment]
Yup, you can do it, take a [look](https://developer.lyft.com/docs/ios-api-wrappers#section-ride-types).

**Comment by PhilippeRiegert** [comment]
@vpolouchkine Thanks so much for the quick answer !
I've just try it and I'm getting the error `no_service_in_area`, so it's working well !!
