### ISSUE TITLE
Can you earn affiliate fees via the iOS SDK?

### ISSUE THREAD

**Issue by mergesort** [lyft/Lyft-iOS-sdk#16]
Hi there,

I was directed here by @keith to answer the question in the issue title. If I can, is there anything special I need to do, or will it detect it via the deep links that come from my app?

Thanks a lot!

**Comment by acityinohio** [comment]
Hi @mergesort—unfortunately no, we no longer have a developer affiliate program.

**Comment by mergesort** [comment]
Alrighty then, thanks for the answer!
