### ISSUE TITLE
Rate limits

### ISSUE THREAD

**Issue by ilyas9** [lyft/Lyft-iOS-sdk#5]
I have a question about the rate limits:
https://developer.lyft.com/docs/rate-limits

Does Lyft differentiate between the User entity and the App entity when rate limits are applied, like Uber does? (https://developer.uber.com/docs/riders/guides/rate-limiting)

Is it possible to have 10000 requests per minute for every access_token?

**Comment by kamloops** [comment]
Hi @ilyas9, currently our rate limits apply to the app in aggregate. We don't currently differentiate at the user vs app level when it comes to incrementing call counts.

So to your second question, calls made on a per access_token basis are still rolled up to your overall rate limit for that given endpoint.

I'm sure you've already seen it, but the rate limits are documented here for your reference: https://developer.lyft.com/docs/rate-limits
