### ISSUE TITLE
Objective C Support

### ISSUE THREAD

**Issue by AmtrakGit** [lyft/Lyft-iOS-sdk#6]
Hi Team,

We have a project which is entirely in objective c. I downloaded the git hub code and followed these steps.

Manual Integration

    Navigate to the SDK GitHub Releases page, download and unzip the archive marked as Latest release.
    Drag the LyftSDK.xcodeproj project into your project's Project Navigator.
    In your project's Build Target, click on the General tab and then, under Embedded Binaries, click the + button.
    Select the LyftSDK.framework under your project.

I was able to add a view in xib and then link the lyftButton class to it. But I can connect the handleClick to the .m file. I did @import LyftSdk in the .m file. I am missing something which is why I am not able to connect anything except the referencing outlet for the lyft button.

I cannot even use any defined methods of LyftButton in Objectivec.m file.

I tried doing this in .m but it could find it.
#import "LyftSDK-Swift.h"

Please let me know if we have support to Objective C and if we do what am I missing.

Thank You
Sunil Gandham

**Comment by vpolouchkine** [comment]
Hey Sunil,

As of today, the SDK only supports Swift code.

Best,
Val
