### ISSUE TITLE
Authorization for scopes 

### ISSUE THREAD

**Issue by Avinodh** [lyft/Lyft-iOS-sdk#8]
Hi! I'm developing an iOS app which would essentially provide the user information such as ETA/Price estimates, and also let the user Request a ride through my app. 

The iOS SDK only provides wrappers for only the endpoints which require default scopes. How would I go about request an auth token for a scope such as (rides.request), and then subsequently make a call to the respective endpoint to request the ride? Any wrappers in the works for this or would I just have to write the requests from the ground up?

**Comment by vpolouchkine** [comment]
Hey Ashvin, 

This is something that we're looking to provide, but I don't have an ETA as of today. For now, it's best to call the auth endpoints outlined here https://developer.lyft.com/docs/authentication and then make the relevant calls "manually".

**Comment by Avinodh** [comment]
@vpolouchkine Thanks a lot for the clarification; I'll lookout for any updates!
